version: "3.8"

services:
  web:
    build: .
    env_file: .env.prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - celery

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  celery:
    build: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env.prod
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
