version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./app:/code/app
      - ./model_files:/code/model_files

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery_worker:
    build: .
    command: celery -A app.celery_worker worker --loglevel=info
    environment:
      - API_KEY=${API_KEY}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./app:/code/app
      - ./model_files:/code/model_files

  flower:
    build: .
    command: celery -A app.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - rabbitmq
      - celery_worker